export const iconCategories = {
  socialMedia: {
    title: 'Social Media',
    description:
      'Iconen van sociale platforms voor links naar profielen. Gebruik alleen als de link echt naar het platform gaat.',
    icons: [
      'utrecht-icon-bluesky',
      'utrecht-icon-facebook',
      'utrecht-icon-instagram',
      'utrecht-icon-mastodon',
      'utrecht-icon-threads',
      'utrecht-icon-twitter',
      'utrecht-icon-x',
      'utrecht-icon-linkedin',
      'utrecht-icon-whatsapp',
      'utrecht-icon-youtube',
      'utrecht-icon-flickr',
      'utrecht-icon-pinterest',
    ],
  },
  functional: {
    title: 'Functionele iconen',
    description:
      'Algemene UI-iconen voor acties, navigatie en status. Inzetbaar in knoppen, linkjes, verduidelijking, lijsten en formulieren.',
    icons: [
      'utrecht-icon-chevron-up',
      'utrecht-icon-chevron-right',
      'utrecht-icon-chevron-down',
      'utrecht-icon-chevron-left',
      'utrecht-icon-minus',
      'utrecht-icon-zoom-plus',
      'utrecht-icon-minus-vertical',
      'utrecht-icon-close',
      'utrecht-icon-hamburger-menu',
      'utrecht-icon-user',
      'utrecht-icon-language',
      'utrecht-icon-search',
      'utrecht-icon-list',
      'utrecht-icon-list-number',
      'utrecht-icon-list-check',
      'utrecht-icon-arrow',
      'utrecht-icon-checkmark',
      'utrecht-icon-cross',
      'utrecht-icon-loupe',
      'utrecht-icon-mail',
      'utrecht-icon-phone',
      'utrecht-icon-coffee',
      'utrecht-icon-report',
    ],
  },
  toptask: {
    title: 'Toptaak iconen',
    description: "Pictogrammen voor de meest gezochte taken en diensten. Gebruik op start- en overzichtspagina's.",
    icons: [
      'utrecht-icon-rijbewijs',
      'utrecht-icon-paspoort',
      'utrecht-icon-melding-klacht',
      'utrecht-icon-verhuizen',
      'utrecht-icon-afval',
      'utrecht-icon-toeslag',
      'utrecht-icon-trouwen',
      'utrecht-icon-afspraak-maken',
      'utrecht-icon-vervoersvoorziening',
      'utrecht-icon-afval-container',
      'utrecht-icon-afval-containerpas',
      'utrecht-icon-afval-kalender',
      'utrecht-icon-afval-scheiden',
      'utrecht-icon-bewijsstukken',
      'utrecht-icon-bijstand',
      'utrecht-icon-bouwproject',
      'utrecht-icon-college-b-w',
      'utrecht-icon-container-bio',
      'utrecht-icon-dakloos',
      'utrecht-icon-parken',
      'utrecht-icon-parkeren-bedrijven',
      'utrecht-icon-parkeren-betalen',
      'utrecht-icon-kroon',
      'utrecht-icon-markt',
      'utrecht-icon-parkeervergunning',
      'utrecht-icon-park',
      'utrecht-icon-grofvuil',
      'utrecht-icon-horeca',
      'utrecht-icon-kerstbomen',
      'utrecht-icon-klachten',
      'utrecht-icon-laadpaal',
      'utrecht-icon-fiets',
      'utrecht-icon-gemeenteraad',
      'utrecht-icon-energie-vergoeding',
      'utrecht-icon-virus',
      'utrecht-icon-werken',
      'utrecht-icon-woning-zoeken',
      'utrecht-icon-verkiezingen',
      'utrecht-icon-vluchtelingen',
      'utrecht-icon-omgevingsvisie',
      'utrecht-icon-omgevingswet',
      'utrecht-icon-openingstijden',
      'utrecht-icon-nieuwsbrief',
    ],
  },
  themaWebsites: {
    title: 'Thema websites iconen',
    description:
      'Iconen voor projectcategorieën op themasites. Handig voor labels en overzichten en om visueele samenhang te creëren binnen de content.',
    icons: [
      'utrecht-icon-bouw-projecten',
      'utrecht-icon-verkeers-projecten',
      'utrecht-icon-groen-projecten',
      'utrecht-icon-energie-projecten',
      'utrecht-icon-standaard-projecten',
    ],
  },
  mapControl: {
    title: 'Map Control',
    description:
      'Besturingsiconen voor interactieve kaarten: filter, lijst en in-/uitzoomen. Uitsluitend binnen kaartcomponenten gebruiken.',
    icons: ['utrecht-icon-filter', 'utrecht-icon-list', 'utrecht-icon-zoomin', 'utrecht-icon-zoomout'],
  },
  wijk: {
    title: 'Iconen voor wijken',
    description: "Wijkspecifieke onderwerpen en activiteiten; bedoeld voor gebruik op wijkpagina's.",
    icons: [
      'utrecht-icon-wijk-denkmee',
      'utrecht-icon-wijk-speelplaats',
      'utrecht-icon-wijk-sport',
      'utrecht-icon-buurtcentra',
      'utrecht-icon-wijk-overlast',
      'utrecht-icon-wijk-projecten',
      'utrecht-icon-wijk-zwemmen',
    ],
  },
  feedback: {
    title: 'Feedback iconen',
    description: '',
    icons: ['utrecht-icon-warning', 'utrecht-icon-error', 'utrecht-icon-information'],
  },
};
