/* eslint-env node */

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  basis: [
    { type: 'category', label: 'Algemeen', items: [{ type: 'autogenerated', dirName: 'tmp/basis' }] },
    { type: 'category', label: 'Redactie', items: [{ type: 'autogenerated', dirName: 'tmp/redactie' }] },
    { type: 'category', label: 'Ontwikkelaars', items: [{ type: 'autogenerated', dirName: 'tmp/ontwikkelaars' }] },
  ],
  components: [{ type: 'autogenerated', dirName: 'componenten' }],
  designrichtlijnen: [{ type: 'autogenerated', dirName: 'tmp/designrichtlijnen' }],
  //  components: [{ type: 'category', label: 'Tekst', items: [{ type: 'autogenerated', dirName: 'componenten/tekst' }] }],
  //  branding: [{ type: 'category', label: 'Branding', items: [{ type: 'autogenerated', dirName: 'componenten/branding' }] }],
  huisstijl: [{ type: 'autogenerated', dirName: 'tmp/huisstijl' }],
  onderzoek: [{ type: 'autogenerated', dirName: 'tmp/gebruikersonderzoek' }],
};
