version: 2

# Documentation:
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-version-updates
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 20
    reviewers:
      - "nl-design-system/sysadmin"
    ignore:
      # Stay at webpack 4 until webpack 5 is fully supported by Storybook
      - dependency-name: "webpack"
        update-types: ["version-update:semver-major"]
      # Stay at React 16 until React 17 is fully supported by Storybook
      - dependency-name: "@types/react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      # Stay at Angular 11 until manual upgrade to Angular 12
      - dependency-name: "@angular/cli"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/compiler-cli"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/core"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@angular/forms"
        update-types: ["version-update:semver-major"]
      - dependency-name: "ng-packagr"
        update-types: ["version-update:semver-major"]
      - dependency-name: "rxjs"
        update-types: ["version-update:semver-major"]
      # `angular-devkit` follows unusual versioning rules.
      # The important thing is to stay on a version matching Angular 11:
      #
      #     npm install --save-dev @angular-devkit/build-angular@v11-lts
      - dependency-name: "@angular-devkit/build-angular"
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
      # Angular Compiler requires TypeScript >=4.0.0 and <4.2.0
      - dependency-name: "typescript"
        update-types:
          ["version-update:semver-major", "version-update:semver-minor"]
