export default {
  extends: ['stylelint-config-standard-scss'],
  plugins: ['stylelint-order', 'stylelint-use-logical'],
  rules: {
    'order/order': ['custom-properties', 'declarations'],
    'order/properties-alphabetical-order': true,
    'scss/at-mixin-pattern': '^[a-z][a-z0-9-_]*$',
    'scss/at-rule-no-unknown': true,
    'scss/dollar-variable-default': true,
    'scss/dollar-variable-first-in-block': [true, { ignore: ['comments', 'imports'] }],
    'scss/dollar-variable-pattern': '^(basis|example|utrecht)-[a-z0-9-]+$',
    'scss/percent-placeholder-pattern': '^(basis|example|utrecht)-[a-z0-9-]+$',
    'scss/operator-no-newline-after': null,
    'scss/at-extend-no-missing-placeholder': null,
    'custom-property-pattern': '^_?(basis|example|denhaag|utrecht)-[a-z0-9-]+$',
    'selector-class-pattern': '^(basis|example|denhaag|utrecht|flo)-[a-z0-9_-]+$',
    'keyframes-name-pattern': '^(basis|example|utrecht)-[a-z0-9-]+$',
    'at-rule-no-unknown': null,
    'block-no-empty': [true],
    'color-no-invalid-hex': [true],
    'comment-no-empty': [true],
    'declaration-block-no-duplicate-properties': [true, { ignore: ['consecutive-duplicates-with-different-values'] }],
    'declaration-block-no-shorthand-property-overrides': [true],
    'font-family-no-duplicate-names': [true],
    'font-family-no-missing-generic-family-keyword': [true],
    'function-calc-no-unspaced-operator': [true],
    'function-linear-gradient-no-nonstandard-direction': [true],
    'keyframe-declaration-no-important': [true],
    'media-feature-name-no-unknown': [true],
    'no-descending-specificity': [true],
    'no-duplicate-at-import-rules': [true],
    'no-duplicate-selectors': [true],
    'no-empty-source': [true],
    'no-invalid-double-slash-comments': [true],
    'property-no-unknown': [true],
    'selector-pseudo-class-no-unknown': [true],
    'selector-pseudo-element-no-unknown': [true],
    'string-no-newline': [true],
    'unit-no-unknown': [true],
    'alpha-value-notation': ['percentage'],
    'hue-degree-notation': ['number'],
    'color-function-notation': ['modern'],
    'length-zero-no-unit': [
      true,
      {
        ignore: ['custom-properties'],
      },
    ],
    'font-weight-notation': [
      'numeric',
      {
        ignore: ['relative'],
      },
    ],
    'function-url-no-scheme-relative': [true],
    'unit-disallowed-list': [['s']],
    'font-family-name-quotes': ['always-unless-keyword'],
    'function-url-quotes': ['always'],
    'declaration-property-value-disallowed-list': [
      {
        'text-align': ['left', 'right'],
      },
    ],
    'property-disallowed-list': [['border', 'margin', 'padding']],
    'selector-max-id': [0],
    'selector-attribute-quotes': ['always'],
    'value-keyword-case': [
      'lower',
      {
        camelCaseSvgKeywords: true,
        ignoreKeywords: [
          'Part',
          'Art',
          'Sect',
          'Div',
          'Index',
          'BlockQuote',
          'Caption',
          'TOC',
          'TOCI',
          'P',
          'H1',
          'H2',
          'H3',
          'H4',
          'H5',
          'H6',
          'OL',
          'UL',
          'LI',
          'Lbl',
          'DL',
          'DL-Div',
          'DT',
          'DD',
          'Span',
          'Quote',
          'Table',
          'BibEntry',
          'Code',
          'Figure',
          'Formula',
          'Artifact',
          'Note',
          'Reference',
        ],
      },
    ],
    'declaration-block-no-redundant-longhand-properties': null,
    'at-rule-empty-line-before': null,
    'rule-empty-line-before': null,
    'property-no-vendor-prefix': null,
    'no-invalid-position-declaration': [true, { ignoreAtRules: ['mixin'] }],
    'csstools/use-logical': 'always',
    'order/properties-order': [
      {
        groupName: 'border',
        properties: [
          'border', // `border` before `border-*`
          'border-collapse',
          'border-color', // `border-color` before `border-*-color`
          'border-image',
          'border-radius', // `border-radius` before `border-*-radius`
          'border-spacing',
          'border-style', // `border-style` before `border-*-style`
          'border-width', // `border-width` before `border-*-width`
          'border-bottom',
          'border-bottom-color',
          'border-bottom-left-radius',
          'border-bottom-right-radius',
          'border-bottom-style',
          'border-bottom-width',
          'border-left',
          'border-left-color',
          'border-left-style',
          'border-left-width',
          'border-right',
          'border-right-color',
          'border-right-style',
          'border-right-width',
          'border-top',
          'border-top-color',
          'border-top-left-radius',
          'border-top-right-radius',
          'border-top-style',
          'border-top-width',
          // CSS Logical properties after CSS Physical properties (typically used as fallback)
          'border-block', // `border-block` before `border-block-*`
          'border-block-color', // `border-block-color` before `border-block-*-color`
          'border-block-style', // `border-block-style` before `border-block-*-style`
          'border-block-width', // `border-block-width` before `border-block-*-width`
          'border-block-end',
          'border-block-end-color',
          'border-block-end-style',
          'border-block-end-width',
          'border-block-start',
          'border-block-start-color',
          'border-block-start-style',
          'border-block-start-width',
          'border-image-outset',
          'border-image-repeat',
          'border-image-slice',
          'border-image-source',
          'border-image-width',
          'border-end-end-radius',
          'border-end-start-radius',
          'border-inline',
          'border-inline-color', // `border-inline-color` before `border-inline-*-color`
          'border-inline-style', // `border-inline-style` before `border-inline-*-style`
          'border-inline-width', // `border-inline-width` before `border-inline-*-width`
          'border-inline-end',
          'border-inline-end-color',
          'border-inline-end-style',
          'border-inline-end-width',
          'border-inline-start',
          'border-inline-start-color',
          'border-inline-start-style',
          'border-inline-start-width',
          'border-start-end-radius',
          'border-start-start-radius',
        ],
      },
    ],
  },
};
