const urls = {
  scenarioAintroductie: './iframe.html?args=&id=klachtenformulier-introductie-a--one&viewMode=story',
  scenarioAscenario: './iframe.html?args=&id=klachtenformulier-scenario-a--one&viewMode=story',
  scenarioAPage1: './iframe.html?args=&id=klachtenformulier-form-pages-stap-1a--one&viewMode=story',
  scenarioAPage2: './iframe.html?args=&id=klachtenformulier-form-pages-stap-2a--one&viewMode=story',
  scenarioAPage3: './iframe.html?args=&id=klachtenformulier-form-pages-stap-3a--one&viewMode=story', //Scenario A, Pagina 3
  scenarioAPage4: './iframe.html?args=&id=klachtenformulier-form-pages-stap-4a--one&viewMode=story',
  scenarioBintroductie: './iframe.html?args=&id=klachtenformulier-introductie-b--one&viewMode=story',
  scenarioBscenario: './iframe.html?args=&id=klachtenformulier-scenario-b--one&viewMode=story',
  scenarioBPage1: './iframe.html?args=&id=klachtenformulier-form-pages-stap-1b--one&viewMode=story',
  scenarioBPage2: './iframe.html?args=&id=klachtenformulier-form-pages-stap-2b--one&viewMode=story',
  scenarioBPage3: './iframe.html?args=&id=klachtenformulier-form-pages-stap-3b--one&viewMode=story',
  scenarioBPage4: './iframe.html?args=&id=klachtenformulier-form-pages-stap-4b--one&viewMode=story',
  fonttestWebpagina: './iframe.html?args=&id=webpagina-font1--one&viewMode=story',
  fonttestStap1: './iframe.html?args=&id=webpagina-event1-font1--one&viewMode=story',
  fonttestStap2: './iframe.html?args=&id=webpagina-event2-font--one&viewMode=story',
  fonttestStapForm: './iframe.html?args=&id=formulier-font1--one&viewMode=story',
  contactformIntroductie: './iframe.html?args=&id=contactformulier-introductie--one&viewMode=story',
  contactformScenario: './iframe.html?args=&id=contactformulier-scenario--one&viewMode=story',
  contactformStap1: './iframe.html?args=&id=contactformulier-stap-1--one&viewMode=story',
  contactformEmail: './iframe.html?args=&id=contactformulier-email--one&viewMode=story',
  contactformIntroductieKTO: './iframe.html?args=&id=contactformulier-introductie-kto-vervolg--one&viewMode=story',
  contactformScenarioKTO: './iframe.html?args=&id=contactformulier-scenario-kto-vervolg--one&viewMode=story',
  contactformStap1KTO: './iframe.html?args=&id=contactformulier-stap-1-kto-vervolg--one&viewMode=story',
  contactformEmailKTO: './iframe.html?args=&id=contactformulier-email-kto-vervolg--one&viewMode=story',
  contactformEmailMobile:
    'https://www.figma.com/proto/J8GosPQdIRzYgXiwB79gks/Formulieren-prototypes--openForms-?page-id=2161%3A44997&node-id=2162-50715&viewport=-3757%2C978%2C0.59&t=SkZGMPwW1sc23wwv-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2162%3A50715',
  contactformEmailDesktop:
    'https://www.figma.com/proto/J8GosPQdIRzYgXiwB79gks/Formulieren-prototypes--openForms-?page-id=2161%3A44997&node-id=4084-5696&viewport=-3757%2C978%2C0.59&t=IOqHaEt7ON9DGEUb-8&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=4084%3A5696&hide-ui=1',
  trouwenNavigatie: './iframe.html?args=&id=trouwen-navigeren--one&viewMode=story',
  trouwenRegelen: './iframe.html?args=&id=trouwen-regelen--one&viewMode=story',
  trouwenRegelenChecklist: './iframe.html?args=&id=trouwen-regelen--one&viewMode=story#regelwerk',
  trouwenVeelgesteldeVragen: './iframe.html?args=&id=trouwen-veelgesteldevragen--one&viewMode=story',
  trouwenSoortenTrouwen: './iframe.html?args=&id=trouwen-soorten-trouwen--one&viewMode=story',
};
export default urls;
