/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UtrechtAlert {
        "type": string;
    }
    interface UtrechtArticle {
    }
    interface UtrechtBackdrop {
        "viewport": boolean;
    }
    interface UtrechtBadgeCounter {
        "locale": string;
        "max": number;
        "value": number;
    }
    interface UtrechtBadgeData {
    }
    interface UtrechtBadgeStatus {
        "status": string;
    }
    interface UtrechtBreadcrumb {
        "json": string;
        "variant": string;
    }
    interface UtrechtButton {
        "appearance": string;
        "busy": boolean;
        "disabled": boolean;
        "type": string;
    }
    interface UtrechtButtonGroup {
    }
    interface UtrechtButtonLink {
        "appearance": string;
        "external": boolean;
        "href": string;
        "placeholder": boolean;
    }
    interface UtrechtCheckbox {
        "checked": boolean;
        "disabled": boolean;
        "readOnly": boolean;
        "value": string;
    }
    interface UtrechtCode {
    }
    interface UtrechtCodeBlock {
    }
    interface UtrechtContactCardTemplate {
    }
    interface UtrechtCustomCheckbox {
        "checked"?: boolean;
        "disabled"?: boolean;
        "indeterminate"?: boolean;
        "invalid"?: boolean;
        "required"?: boolean;
    }
    interface UtrechtDigidButton {
        "type": string;
    }
    interface UtrechtDigidLogo {
    }
    interface UtrechtDocument {
    }
    interface UtrechtEherkenningLogo {
    }
    interface UtrechtEidasLogo {
    }
    interface UtrechtEmphasis {
    }
    interface UtrechtFormFieldCheckbox {
        "checked": boolean;
        "disabled": boolean;
        "invalid": boolean;
        "label": boolean;
        "required": boolean;
    }
    interface UtrechtFormFieldDescription {
        "status"?: string;
    }
    interface UtrechtFormFieldTextarea {
        "disabled": boolean;
        "invalid": boolean;
        "placeholder": string;
        "readOnly": boolean;
        "required": boolean;
        "value": string;
    }
    interface UtrechtFormFieldTextbox {
        "autoComplete": string;
        "disabled": boolean;
        "invalid": boolean;
        "max": string;
        "min": string;
        "pattern": string;
        "placeholder": string;
        "readOnly": boolean;
        "required": boolean;
        "type": string;
        "value": string;
    }
    interface UtrechtFormToggle {
        "checked": boolean;
        "disabled": boolean;
    }
    interface UtrechtHeading {
        /**
          * Heading level
         */
        "level": number;
    }
    interface UtrechtHeading1 {
    }
    interface UtrechtHeading2 {
    }
    interface UtrechtHeading3 {
    }
    interface UtrechtHeading4 {
    }
    interface UtrechtHeading5 {
    }
    interface UtrechtHeading6 {
    }
    interface UtrechtHeadingGroup {
    }
    interface UtrechtHtmlContent {
    }
    interface UtrechtIcon {
    }
    interface UtrechtLink {
        "href": string;
    }
    interface UtrechtLinkButton {
        "disabled": boolean;
        "inline": boolean;
        "pressed": boolean;
        "type": string;
    }
    interface UtrechtLogo {
    }
    interface UtrechtLogoButton {
        "type": string;
    }
    interface UtrechtMapMarker {
    }
    interface UtrechtMark {
    }
    interface UtrechtNumberValue {
        "value": number | string;
    }
    /**
     * @license EUPL-1.2
     * Copyright (c) 2021 Gemeente Utrecht
     */
    interface UtrechtPage {
    }
    /**
     * @license EUPL-1.2
     * Copyright (c) 2021 Gemeente Utrecht
     */
    interface UtrechtPageContent {
    }
    /**
     * @license EUPL-1.2
     * Copyright (c) 2021 Gemeente Utrecht
     */
    interface UtrechtPageFooter {
    }
    /**
     * @license EUPL-1.2
     * Copyright (c) 2021 Gemeente Utrecht
     */
    interface UtrechtPageHeader {
    }
    interface UtrechtPagination {
        "currentIndex": number;
        "links": string;
        "next": string;
        "prev": string;
    }
    interface UtrechtParagraph {
        /**
          * Lead paragraph
         */
        "lead": boolean;
    }
    interface UtrechtPreHeading {
    }
    interface UtrechtSeparator {
    }
    interface UtrechtSidenav {
        "json": string;
    }
    interface UtrechtSkipLink {
        "href": string;
    }
    interface UtrechtSpotlightSection {
        "appearance": string;
    }
    interface UtrechtTable {
    }
    interface UtrechtTableBody {
    }
    interface UtrechtTableCaption {
    }
    interface UtrechtTableCell {
    }
    interface UtrechtTableFooter {
    }
    interface UtrechtTableHeader {
    }
    interface UtrechtTableHeaderCell {
        "scope": 'col' | 'row';
    }
    interface UtrechtTableRow {
    }
    interface UtrechtTextbox {
        "autoComplete": string;
        "disabled": boolean;
        "invalid": boolean;
        "max": string;
        "min": string;
        "pattern": string;
        "placeholder": string;
        "readOnly": boolean;
        "required": boolean;
        "type": string;
        "value": string;
    }
    interface UtrechtUrl {
    }
}
export interface UtrechtButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUtrechtButtonElement;
}
export interface UtrechtCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUtrechtCheckboxElement;
}
export interface UtrechtFormFieldCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUtrechtFormFieldCheckboxElement;
}
export interface UtrechtFormFieldTextareaCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUtrechtFormFieldTextareaElement;
}
export interface UtrechtFormFieldTextboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUtrechtFormFieldTextboxElement;
}
export interface UtrechtFormToggleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUtrechtFormToggleElement;
}
export interface UtrechtTextboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLUtrechtTextboxElement;
}
declare global {
    interface HTMLUtrechtAlertElement extends Components.UtrechtAlert, HTMLStencilElement {
    }
    var HTMLUtrechtAlertElement: {
        prototype: HTMLUtrechtAlertElement;
        new (): HTMLUtrechtAlertElement;
    };
    interface HTMLUtrechtArticleElement extends Components.UtrechtArticle, HTMLStencilElement {
    }
    var HTMLUtrechtArticleElement: {
        prototype: HTMLUtrechtArticleElement;
        new (): HTMLUtrechtArticleElement;
    };
    interface HTMLUtrechtBackdropElement extends Components.UtrechtBackdrop, HTMLStencilElement {
    }
    var HTMLUtrechtBackdropElement: {
        prototype: HTMLUtrechtBackdropElement;
        new (): HTMLUtrechtBackdropElement;
    };
    interface HTMLUtrechtBadgeCounterElement extends Components.UtrechtBadgeCounter, HTMLStencilElement {
    }
    var HTMLUtrechtBadgeCounterElement: {
        prototype: HTMLUtrechtBadgeCounterElement;
        new (): HTMLUtrechtBadgeCounterElement;
    };
    interface HTMLUtrechtBadgeDataElement extends Components.UtrechtBadgeData, HTMLStencilElement {
    }
    var HTMLUtrechtBadgeDataElement: {
        prototype: HTMLUtrechtBadgeDataElement;
        new (): HTMLUtrechtBadgeDataElement;
    };
    interface HTMLUtrechtBadgeStatusElement extends Components.UtrechtBadgeStatus, HTMLStencilElement {
    }
    var HTMLUtrechtBadgeStatusElement: {
        prototype: HTMLUtrechtBadgeStatusElement;
        new (): HTMLUtrechtBadgeStatusElement;
    };
    interface HTMLUtrechtBreadcrumbElement extends Components.UtrechtBreadcrumb, HTMLStencilElement {
    }
    var HTMLUtrechtBreadcrumbElement: {
        prototype: HTMLUtrechtBreadcrumbElement;
        new (): HTMLUtrechtBreadcrumbElement;
    };
    interface HTMLUtrechtButtonElement extends Components.UtrechtButton, HTMLStencilElement {
    }
    var HTMLUtrechtButtonElement: {
        prototype: HTMLUtrechtButtonElement;
        new (): HTMLUtrechtButtonElement;
    };
    interface HTMLUtrechtButtonGroupElement extends Components.UtrechtButtonGroup, HTMLStencilElement {
    }
    var HTMLUtrechtButtonGroupElement: {
        prototype: HTMLUtrechtButtonGroupElement;
        new (): HTMLUtrechtButtonGroupElement;
    };
    interface HTMLUtrechtButtonLinkElement extends Components.UtrechtButtonLink, HTMLStencilElement {
    }
    var HTMLUtrechtButtonLinkElement: {
        prototype: HTMLUtrechtButtonLinkElement;
        new (): HTMLUtrechtButtonLinkElement;
    };
    interface HTMLUtrechtCheckboxElement extends Components.UtrechtCheckbox, HTMLStencilElement {
    }
    var HTMLUtrechtCheckboxElement: {
        prototype: HTMLUtrechtCheckboxElement;
        new (): HTMLUtrechtCheckboxElement;
    };
    interface HTMLUtrechtCodeElement extends Components.UtrechtCode, HTMLStencilElement {
    }
    var HTMLUtrechtCodeElement: {
        prototype: HTMLUtrechtCodeElement;
        new (): HTMLUtrechtCodeElement;
    };
    interface HTMLUtrechtCodeBlockElement extends Components.UtrechtCodeBlock, HTMLStencilElement {
    }
    var HTMLUtrechtCodeBlockElement: {
        prototype: HTMLUtrechtCodeBlockElement;
        new (): HTMLUtrechtCodeBlockElement;
    };
    interface HTMLUtrechtContactCardTemplateElement extends Components.UtrechtContactCardTemplate, HTMLStencilElement {
    }
    var HTMLUtrechtContactCardTemplateElement: {
        prototype: HTMLUtrechtContactCardTemplateElement;
        new (): HTMLUtrechtContactCardTemplateElement;
    };
    interface HTMLUtrechtCustomCheckboxElement extends Components.UtrechtCustomCheckbox, HTMLStencilElement {
    }
    var HTMLUtrechtCustomCheckboxElement: {
        prototype: HTMLUtrechtCustomCheckboxElement;
        new (): HTMLUtrechtCustomCheckboxElement;
    };
    interface HTMLUtrechtDigidButtonElement extends Components.UtrechtDigidButton, HTMLStencilElement {
    }
    var HTMLUtrechtDigidButtonElement: {
        prototype: HTMLUtrechtDigidButtonElement;
        new (): HTMLUtrechtDigidButtonElement;
    };
    interface HTMLUtrechtDigidLogoElement extends Components.UtrechtDigidLogo, HTMLStencilElement {
    }
    var HTMLUtrechtDigidLogoElement: {
        prototype: HTMLUtrechtDigidLogoElement;
        new (): HTMLUtrechtDigidLogoElement;
    };
    interface HTMLUtrechtDocumentElement extends Components.UtrechtDocument, HTMLStencilElement {
    }
    var HTMLUtrechtDocumentElement: {
        prototype: HTMLUtrechtDocumentElement;
        new (): HTMLUtrechtDocumentElement;
    };
    interface HTMLUtrechtEherkenningLogoElement extends Components.UtrechtEherkenningLogo, HTMLStencilElement {
    }
    var HTMLUtrechtEherkenningLogoElement: {
        prototype: HTMLUtrechtEherkenningLogoElement;
        new (): HTMLUtrechtEherkenningLogoElement;
    };
    interface HTMLUtrechtEidasLogoElement extends Components.UtrechtEidasLogo, HTMLStencilElement {
    }
    var HTMLUtrechtEidasLogoElement: {
        prototype: HTMLUtrechtEidasLogoElement;
        new (): HTMLUtrechtEidasLogoElement;
    };
    interface HTMLUtrechtEmphasisElement extends Components.UtrechtEmphasis, HTMLStencilElement {
    }
    var HTMLUtrechtEmphasisElement: {
        prototype: HTMLUtrechtEmphasisElement;
        new (): HTMLUtrechtEmphasisElement;
    };
    interface HTMLUtrechtFormFieldCheckboxElement extends Components.UtrechtFormFieldCheckbox, HTMLStencilElement {
    }
    var HTMLUtrechtFormFieldCheckboxElement: {
        prototype: HTMLUtrechtFormFieldCheckboxElement;
        new (): HTMLUtrechtFormFieldCheckboxElement;
    };
    interface HTMLUtrechtFormFieldDescriptionElement extends Components.UtrechtFormFieldDescription, HTMLStencilElement {
    }
    var HTMLUtrechtFormFieldDescriptionElement: {
        prototype: HTMLUtrechtFormFieldDescriptionElement;
        new (): HTMLUtrechtFormFieldDescriptionElement;
    };
    interface HTMLUtrechtFormFieldTextareaElement extends Components.UtrechtFormFieldTextarea, HTMLStencilElement {
    }
    var HTMLUtrechtFormFieldTextareaElement: {
        prototype: HTMLUtrechtFormFieldTextareaElement;
        new (): HTMLUtrechtFormFieldTextareaElement;
    };
    interface HTMLUtrechtFormFieldTextboxElement extends Components.UtrechtFormFieldTextbox, HTMLStencilElement {
    }
    var HTMLUtrechtFormFieldTextboxElement: {
        prototype: HTMLUtrechtFormFieldTextboxElement;
        new (): HTMLUtrechtFormFieldTextboxElement;
    };
    interface HTMLUtrechtFormToggleElement extends Components.UtrechtFormToggle, HTMLStencilElement {
    }
    var HTMLUtrechtFormToggleElement: {
        prototype: HTMLUtrechtFormToggleElement;
        new (): HTMLUtrechtFormToggleElement;
    };
    interface HTMLUtrechtHeadingElement extends Components.UtrechtHeading, HTMLStencilElement {
    }
    var HTMLUtrechtHeadingElement: {
        prototype: HTMLUtrechtHeadingElement;
        new (): HTMLUtrechtHeadingElement;
    };
    interface HTMLUtrechtHeading1Element extends Components.UtrechtHeading1, HTMLStencilElement {
    }
    var HTMLUtrechtHeading1Element: {
        prototype: HTMLUtrechtHeading1Element;
        new (): HTMLUtrechtHeading1Element;
    };
    interface HTMLUtrechtHeading2Element extends Components.UtrechtHeading2, HTMLStencilElement {
    }
    var HTMLUtrechtHeading2Element: {
        prototype: HTMLUtrechtHeading2Element;
        new (): HTMLUtrechtHeading2Element;
    };
    interface HTMLUtrechtHeading3Element extends Components.UtrechtHeading3, HTMLStencilElement {
    }
    var HTMLUtrechtHeading3Element: {
        prototype: HTMLUtrechtHeading3Element;
        new (): HTMLUtrechtHeading3Element;
    };
    interface HTMLUtrechtHeading4Element extends Components.UtrechtHeading4, HTMLStencilElement {
    }
    var HTMLUtrechtHeading4Element: {
        prototype: HTMLUtrechtHeading4Element;
        new (): HTMLUtrechtHeading4Element;
    };
    interface HTMLUtrechtHeading5Element extends Components.UtrechtHeading5, HTMLStencilElement {
    }
    var HTMLUtrechtHeading5Element: {
        prototype: HTMLUtrechtHeading5Element;
        new (): HTMLUtrechtHeading5Element;
    };
    interface HTMLUtrechtHeading6Element extends Components.UtrechtHeading6, HTMLStencilElement {
    }
    var HTMLUtrechtHeading6Element: {
        prototype: HTMLUtrechtHeading6Element;
        new (): HTMLUtrechtHeading6Element;
    };
    interface HTMLUtrechtHeadingGroupElement extends Components.UtrechtHeadingGroup, HTMLStencilElement {
    }
    var HTMLUtrechtHeadingGroupElement: {
        prototype: HTMLUtrechtHeadingGroupElement;
        new (): HTMLUtrechtHeadingGroupElement;
    };
    interface HTMLUtrechtHtmlContentElement extends Components.UtrechtHtmlContent, HTMLStencilElement {
    }
    var HTMLUtrechtHtmlContentElement: {
        prototype: HTMLUtrechtHtmlContentElement;
        new (): HTMLUtrechtHtmlContentElement;
    };
    interface HTMLUtrechtIconElement extends Components.UtrechtIcon, HTMLStencilElement {
    }
    var HTMLUtrechtIconElement: {
        prototype: HTMLUtrechtIconElement;
        new (): HTMLUtrechtIconElement;
    };
    interface HTMLUtrechtLinkElement extends Components.UtrechtLink, HTMLStencilElement {
    }
    var HTMLUtrechtLinkElement: {
        prototype: HTMLUtrechtLinkElement;
        new (): HTMLUtrechtLinkElement;
    };
    interface HTMLUtrechtLinkButtonElement extends Components.UtrechtLinkButton, HTMLStencilElement {
    }
    var HTMLUtrechtLinkButtonElement: {
        prototype: HTMLUtrechtLinkButtonElement;
        new (): HTMLUtrechtLinkButtonElement;
    };
    interface HTMLUtrechtLogoElement extends Components.UtrechtLogo, HTMLStencilElement {
    }
    var HTMLUtrechtLogoElement: {
        prototype: HTMLUtrechtLogoElement;
        new (): HTMLUtrechtLogoElement;
    };
    interface HTMLUtrechtLogoButtonElement extends Components.UtrechtLogoButton, HTMLStencilElement {
    }
    var HTMLUtrechtLogoButtonElement: {
        prototype: HTMLUtrechtLogoButtonElement;
        new (): HTMLUtrechtLogoButtonElement;
    };
    interface HTMLUtrechtMapMarkerElement extends Components.UtrechtMapMarker, HTMLStencilElement {
    }
    var HTMLUtrechtMapMarkerElement: {
        prototype: HTMLUtrechtMapMarkerElement;
        new (): HTMLUtrechtMapMarkerElement;
    };
    interface HTMLUtrechtMarkElement extends Components.UtrechtMark, HTMLStencilElement {
    }
    var HTMLUtrechtMarkElement: {
        prototype: HTMLUtrechtMarkElement;
        new (): HTMLUtrechtMarkElement;
    };
    interface HTMLUtrechtNumberValueElement extends Components.UtrechtNumberValue, HTMLStencilElement {
    }
    var HTMLUtrechtNumberValueElement: {
        prototype: HTMLUtrechtNumberValueElement;
        new (): HTMLUtrechtNumberValueElement;
    };
    /**
     * @license EUPL-1.2
     * Copyright (c) 2021 Gemeente Utrecht
     */
    interface HTMLUtrechtPageElement extends Components.UtrechtPage, HTMLStencilElement {
    }
    var HTMLUtrechtPageElement: {
        prototype: HTMLUtrechtPageElement;
        new (): HTMLUtrechtPageElement;
    };
    /**
     * @license EUPL-1.2
     * Copyright (c) 2021 Gemeente Utrecht
     */
    interface HTMLUtrechtPageContentElement extends Components.UtrechtPageContent, HTMLStencilElement {
    }
    var HTMLUtrechtPageContentElement: {
        prototype: HTMLUtrechtPageContentElement;
        new (): HTMLUtrechtPageContentElement;
    };
    /**
     * @license EUPL-1.2
     * Copyright (c) 2021 Gemeente Utrecht
     */
    interface HTMLUtrechtPageFooterElement extends Components.UtrechtPageFooter, HTMLStencilElement {
    }
    var HTMLUtrechtPageFooterElement: {
        prototype: HTMLUtrechtPageFooterElement;
        new (): HTMLUtrechtPageFooterElement;
    };
    /**
     * @license EUPL-1.2
     * Copyright (c) 2021 Gemeente Utrecht
     */
    interface HTMLUtrechtPageHeaderElement extends Components.UtrechtPageHeader, HTMLStencilElement {
    }
    var HTMLUtrechtPageHeaderElement: {
        prototype: HTMLUtrechtPageHeaderElement;
        new (): HTMLUtrechtPageHeaderElement;
    };
    interface HTMLUtrechtPaginationElement extends Components.UtrechtPagination, HTMLStencilElement {
    }
    var HTMLUtrechtPaginationElement: {
        prototype: HTMLUtrechtPaginationElement;
        new (): HTMLUtrechtPaginationElement;
    };
    interface HTMLUtrechtParagraphElement extends Components.UtrechtParagraph, HTMLStencilElement {
    }
    var HTMLUtrechtParagraphElement: {
        prototype: HTMLUtrechtParagraphElement;
        new (): HTMLUtrechtParagraphElement;
    };
    interface HTMLUtrechtPreHeadingElement extends Components.UtrechtPreHeading, HTMLStencilElement {
    }
    var HTMLUtrechtPreHeadingElement: {
        prototype: HTMLUtrechtPreHeadingElement;
        new (): HTMLUtrechtPreHeadingElement;
    };
    interface HTMLUtrechtSeparatorElement extends Components.UtrechtSeparator, HTMLStencilElement {
    }
    var HTMLUtrechtSeparatorElement: {
        prototype: HTMLUtrechtSeparatorElement;
        new (): HTMLUtrechtSeparatorElement;
    };
    interface HTMLUtrechtSidenavElement extends Components.UtrechtSidenav, HTMLStencilElement {
    }
    var HTMLUtrechtSidenavElement: {
        prototype: HTMLUtrechtSidenavElement;
        new (): HTMLUtrechtSidenavElement;
    };
    interface HTMLUtrechtSkipLinkElement extends Components.UtrechtSkipLink, HTMLStencilElement {
    }
    var HTMLUtrechtSkipLinkElement: {
        prototype: HTMLUtrechtSkipLinkElement;
        new (): HTMLUtrechtSkipLinkElement;
    };
    interface HTMLUtrechtSpotlightSectionElement extends Components.UtrechtSpotlightSection, HTMLStencilElement {
    }
    var HTMLUtrechtSpotlightSectionElement: {
        prototype: HTMLUtrechtSpotlightSectionElement;
        new (): HTMLUtrechtSpotlightSectionElement;
    };
    interface HTMLUtrechtTableElement extends Components.UtrechtTable, HTMLStencilElement {
    }
    var HTMLUtrechtTableElement: {
        prototype: HTMLUtrechtTableElement;
        new (): HTMLUtrechtTableElement;
    };
    interface HTMLUtrechtTableBodyElement extends Components.UtrechtTableBody, HTMLStencilElement {
    }
    var HTMLUtrechtTableBodyElement: {
        prototype: HTMLUtrechtTableBodyElement;
        new (): HTMLUtrechtTableBodyElement;
    };
    interface HTMLUtrechtTableCaptionElement extends Components.UtrechtTableCaption, HTMLStencilElement {
    }
    var HTMLUtrechtTableCaptionElement: {
        prototype: HTMLUtrechtTableCaptionElement;
        new (): HTMLUtrechtTableCaptionElement;
    };
    interface HTMLUtrechtTableCellElement extends Components.UtrechtTableCell, HTMLStencilElement {
    }
    var HTMLUtrechtTableCellElement: {
        prototype: HTMLUtrechtTableCellElement;
        new (): HTMLUtrechtTableCellElement;
    };
    interface HTMLUtrechtTableFooterElement extends Components.UtrechtTableFooter, HTMLStencilElement {
    }
    var HTMLUtrechtTableFooterElement: {
        prototype: HTMLUtrechtTableFooterElement;
        new (): HTMLUtrechtTableFooterElement;
    };
    interface HTMLUtrechtTableHeaderElement extends Components.UtrechtTableHeader, HTMLStencilElement {
    }
    var HTMLUtrechtTableHeaderElement: {
        prototype: HTMLUtrechtTableHeaderElement;
        new (): HTMLUtrechtTableHeaderElement;
    };
    interface HTMLUtrechtTableHeaderCellElement extends Components.UtrechtTableHeaderCell, HTMLStencilElement {
    }
    var HTMLUtrechtTableHeaderCellElement: {
        prototype: HTMLUtrechtTableHeaderCellElement;
        new (): HTMLUtrechtTableHeaderCellElement;
    };
    interface HTMLUtrechtTableRowElement extends Components.UtrechtTableRow, HTMLStencilElement {
    }
    var HTMLUtrechtTableRowElement: {
        prototype: HTMLUtrechtTableRowElement;
        new (): HTMLUtrechtTableRowElement;
    };
    interface HTMLUtrechtTextboxElement extends Components.UtrechtTextbox, HTMLStencilElement {
    }
    var HTMLUtrechtTextboxElement: {
        prototype: HTMLUtrechtTextboxElement;
        new (): HTMLUtrechtTextboxElement;
    };
    interface HTMLUtrechtUrlElement extends Components.UtrechtUrl, HTMLStencilElement {
    }
    var HTMLUtrechtUrlElement: {
        prototype: HTMLUtrechtUrlElement;
        new (): HTMLUtrechtUrlElement;
    };
    interface HTMLElementTagNameMap {
        "utrecht-alert": HTMLUtrechtAlertElement;
        "utrecht-article": HTMLUtrechtArticleElement;
        "utrecht-backdrop": HTMLUtrechtBackdropElement;
        "utrecht-badge-counter": HTMLUtrechtBadgeCounterElement;
        "utrecht-badge-data": HTMLUtrechtBadgeDataElement;
        "utrecht-badge-status": HTMLUtrechtBadgeStatusElement;
        "utrecht-breadcrumb": HTMLUtrechtBreadcrumbElement;
        "utrecht-button": HTMLUtrechtButtonElement;
        "utrecht-button-group": HTMLUtrechtButtonGroupElement;
        "utrecht-button-link": HTMLUtrechtButtonLinkElement;
        "utrecht-checkbox": HTMLUtrechtCheckboxElement;
        "utrecht-code": HTMLUtrechtCodeElement;
        "utrecht-code-block": HTMLUtrechtCodeBlockElement;
        "utrecht-contact-card-template": HTMLUtrechtContactCardTemplateElement;
        "utrecht-custom-checkbox": HTMLUtrechtCustomCheckboxElement;
        "utrecht-digid-button": HTMLUtrechtDigidButtonElement;
        "utrecht-digid-logo": HTMLUtrechtDigidLogoElement;
        "utrecht-document": HTMLUtrechtDocumentElement;
        "utrecht-eherkenning-logo": HTMLUtrechtEherkenningLogoElement;
        "utrecht-eidas-logo": HTMLUtrechtEidasLogoElement;
        "utrecht-emphasis": HTMLUtrechtEmphasisElement;
        "utrecht-form-field-checkbox": HTMLUtrechtFormFieldCheckboxElement;
        "utrecht-form-field-description": HTMLUtrechtFormFieldDescriptionElement;
        "utrecht-form-field-textarea": HTMLUtrechtFormFieldTextareaElement;
        "utrecht-form-field-textbox": HTMLUtrechtFormFieldTextboxElement;
        "utrecht-form-toggle": HTMLUtrechtFormToggleElement;
        "utrecht-heading": HTMLUtrechtHeadingElement;
        "utrecht-heading-1": HTMLUtrechtHeading1Element;
        "utrecht-heading-2": HTMLUtrechtHeading2Element;
        "utrecht-heading-3": HTMLUtrechtHeading3Element;
        "utrecht-heading-4": HTMLUtrechtHeading4Element;
        "utrecht-heading-5": HTMLUtrechtHeading5Element;
        "utrecht-heading-6": HTMLUtrechtHeading6Element;
        "utrecht-heading-group": HTMLUtrechtHeadingGroupElement;
        "utrecht-html-content": HTMLUtrechtHtmlContentElement;
        "utrecht-icon": HTMLUtrechtIconElement;
        "utrecht-link": HTMLUtrechtLinkElement;
        "utrecht-link-button": HTMLUtrechtLinkButtonElement;
        "utrecht-logo": HTMLUtrechtLogoElement;
        "utrecht-logo-button": HTMLUtrechtLogoButtonElement;
        "utrecht-map-marker": HTMLUtrechtMapMarkerElement;
        "utrecht-mark": HTMLUtrechtMarkElement;
        "utrecht-number-value": HTMLUtrechtNumberValueElement;
        "utrecht-page": HTMLUtrechtPageElement;
        "utrecht-page-content": HTMLUtrechtPageContentElement;
        "utrecht-page-footer": HTMLUtrechtPageFooterElement;
        "utrecht-page-header": HTMLUtrechtPageHeaderElement;
        "utrecht-pagination": HTMLUtrechtPaginationElement;
        "utrecht-paragraph": HTMLUtrechtParagraphElement;
        "utrecht-pre-heading": HTMLUtrechtPreHeadingElement;
        "utrecht-separator": HTMLUtrechtSeparatorElement;
        "utrecht-sidenav": HTMLUtrechtSidenavElement;
        "utrecht-skip-link": HTMLUtrechtSkipLinkElement;
        "utrecht-spotlight-section": HTMLUtrechtSpotlightSectionElement;
        "utrecht-table": HTMLUtrechtTableElement;
        "utrecht-table-body": HTMLUtrechtTableBodyElement;
        "utrecht-table-caption": HTMLUtrechtTableCaptionElement;
        "utrecht-table-cell": HTMLUtrechtTableCellElement;
        "utrecht-table-footer": HTMLUtrechtTableFooterElement;
        "utrecht-table-header": HTMLUtrechtTableHeaderElement;
        "utrecht-table-header-cell": HTMLUtrechtTableHeaderCellElement;
        "utrecht-table-row": HTMLUtrechtTableRowElement;
        "utrecht-textbox": HTMLUtrechtTextboxElement;
        "utrecht-url": HTMLUtrechtUrlElement;
    }
}
declare namespace LocalJSX {
    interface UtrechtAlert {
        "type"?: string;
    }
    interface UtrechtArticle {
    }
    interface UtrechtBackdrop {
        "viewport"?: boolean;
    }
    interface UtrechtBadgeCounter {
        "locale"?: string;
        "max"?: number;
        "value"?: number;
    }
    interface UtrechtBadgeData {
    }
    interface UtrechtBadgeStatus {
        "status"?: string;
    }
    interface UtrechtBreadcrumb {
        "json"?: string;
        "variant"?: string;
    }
    interface UtrechtButton {
        "appearance"?: string;
        "busy"?: boolean;
        "disabled"?: boolean;
        "onUtrechtRequestReset"?: (event: UtrechtButtonCustomEvent<any>) => void;
        "onUtrechtRequestSubmit"?: (event: UtrechtButtonCustomEvent<any>) => void;
        "type"?: string;
    }
    interface UtrechtButtonGroup {
    }
    interface UtrechtButtonLink {
        "appearance"?: string;
        "external"?: boolean;
        "href"?: string;
        "placeholder"?: boolean;
    }
    interface UtrechtCheckbox {
        "checked"?: boolean;
        "disabled"?: boolean;
        "onUtrechtBlur"?: (event: UtrechtCheckboxCustomEvent<any>) => void;
        "onUtrechtChange"?: (event: UtrechtCheckboxCustomEvent<any>) => void;
        "onUtrechtFocus"?: (event: UtrechtCheckboxCustomEvent<any>) => void;
        "onUtrechtInput"?: (event: UtrechtCheckboxCustomEvent<any>) => void;
        "readOnly"?: boolean;
        "value"?: string;
    }
    interface UtrechtCode {
    }
    interface UtrechtCodeBlock {
    }
    interface UtrechtContactCardTemplate {
    }
    interface UtrechtCustomCheckbox {
        "checked"?: boolean;
        "disabled"?: boolean;
        "indeterminate"?: boolean;
        "invalid"?: boolean;
        "required"?: boolean;
    }
    interface UtrechtDigidButton {
        "type"?: string;
    }
    interface UtrechtDigidLogo {
    }
    interface UtrechtDocument {
    }
    interface UtrechtEherkenningLogo {
    }
    interface UtrechtEidasLogo {
    }
    interface UtrechtEmphasis {
    }
    interface UtrechtFormFieldCheckbox {
        "checked"?: boolean;
        "disabled"?: boolean;
        "invalid"?: boolean;
        "label"?: boolean;
        "onUtrechtBlur"?: (event: UtrechtFormFieldCheckboxCustomEvent<any>) => void;
        "onUtrechtChange"?: (event: UtrechtFormFieldCheckboxCustomEvent<any>) => void;
        "onUtrechtFocus"?: (event: UtrechtFormFieldCheckboxCustomEvent<any>) => void;
        "onUtrechtInput"?: (event: UtrechtFormFieldCheckboxCustomEvent<any>) => void;
        "required"?: boolean;
    }
    interface UtrechtFormFieldDescription {
        "status"?: string;
    }
    interface UtrechtFormFieldTextarea {
        "disabled"?: boolean;
        "invalid"?: boolean;
        "onUtrechtBlur"?: (event: UtrechtFormFieldTextareaCustomEvent<any>) => void;
        "onUtrechtChange"?: (event: UtrechtFormFieldTextareaCustomEvent<any>) => void;
        "onUtrechtFocus"?: (event: UtrechtFormFieldTextareaCustomEvent<any>) => void;
        "onUtrechtInput"?: (event: UtrechtFormFieldTextareaCustomEvent<any>) => void;
        "placeholder"?: string;
        "readOnly"?: boolean;
        "required"?: boolean;
        "value"?: string;
    }
    interface UtrechtFormFieldTextbox {
        "autoComplete"?: string;
        "disabled"?: boolean;
        "invalid"?: boolean;
        "max"?: string;
        "min"?: string;
        "onUtrechtBlur"?: (event: UtrechtFormFieldTextboxCustomEvent<any>) => void;
        "onUtrechtChange"?: (event: UtrechtFormFieldTextboxCustomEvent<any>) => void;
        "onUtrechtFocus"?: (event: UtrechtFormFieldTextboxCustomEvent<any>) => void;
        "onUtrechtInput"?: (event: UtrechtFormFieldTextboxCustomEvent<any>) => void;
        "pattern"?: string;
        "placeholder"?: string;
        "readOnly"?: boolean;
        "required"?: boolean;
        "type"?: string;
        "value"?: string;
    }
    interface UtrechtFormToggle {
        "checked"?: boolean;
        "disabled"?: boolean;
        "onUtrechtBlur"?: (event: UtrechtFormToggleCustomEvent<any>) => void;
        "onUtrechtChange"?: (event: UtrechtFormToggleCustomEvent<any>) => void;
        "onUtrechtFocus"?: (event: UtrechtFormToggleCustomEvent<any>) => void;
        "onUtrechtInput"?: (event: UtrechtFormToggleCustomEvent<any>) => void;
    }
    interface UtrechtHeading {
        /**
          * Heading level
         */
        "level"?: number;
    }
    interface UtrechtHeading1 {
    }
    interface UtrechtHeading2 {
    }
    interface UtrechtHeading3 {
    }
    interface UtrechtHeading4 {
    }
    interface UtrechtHeading5 {
    }
    interface UtrechtHeading6 {
    }
    interface UtrechtHeadingGroup {
    }
    interface UtrechtHtmlContent {
    }
    interface UtrechtIcon {
    }
    interface UtrechtLink {
        "href"?: string;
    }
    interface UtrechtLinkButton {
        "disabled"?: boolean;
        "inline"?: boolean;
        "pressed"?: boolean;
        "type"?: string;
    }
    interface UtrechtLogo {
    }
    interface UtrechtLogoButton {
        "type"?: string;
    }
    interface UtrechtMapMarker {
    }
    interface UtrechtMark {
    }
    interface UtrechtNumberValue {
        "value"?: number | string;
    }
    /**
     * @license EUPL-1.2
     * Copyright (c) 2021 Gemeente Utrecht
     */
    interface UtrechtPage {
    }
    /**
     * @license EUPL-1.2
     * Copyright (c) 2021 Gemeente Utrecht
     */
    interface UtrechtPageContent {
    }
    /**
     * @license EUPL-1.2
     * Copyright (c) 2021 Gemeente Utrecht
     */
    interface UtrechtPageFooter {
    }
    /**
     * @license EUPL-1.2
     * Copyright (c) 2021 Gemeente Utrecht
     */
    interface UtrechtPageHeader {
    }
    interface UtrechtPagination {
        "currentIndex"?: number;
        "links"?: string;
        "next"?: string;
        "prev"?: string;
    }
    interface UtrechtParagraph {
        /**
          * Lead paragraph
         */
        "lead"?: boolean;
    }
    interface UtrechtPreHeading {
    }
    interface UtrechtSeparator {
    }
    interface UtrechtSidenav {
        "json"?: string;
    }
    interface UtrechtSkipLink {
        "href"?: string;
    }
    interface UtrechtSpotlightSection {
        "appearance"?: string;
    }
    interface UtrechtTable {
    }
    interface UtrechtTableBody {
    }
    interface UtrechtTableCaption {
    }
    interface UtrechtTableCell {
    }
    interface UtrechtTableFooter {
    }
    interface UtrechtTableHeader {
    }
    interface UtrechtTableHeaderCell {
        "scope"?: 'col' | 'row';
    }
    interface UtrechtTableRow {
    }
    interface UtrechtTextbox {
        "autoComplete"?: string;
        "disabled"?: boolean;
        "invalid"?: boolean;
        "max"?: string;
        "min"?: string;
        "onUtrechtBlur"?: (event: UtrechtTextboxCustomEvent<any>) => void;
        "onUtrechtChange"?: (event: UtrechtTextboxCustomEvent<any>) => void;
        "onUtrechtFocus"?: (event: UtrechtTextboxCustomEvent<any>) => void;
        "onUtrechtInput"?: (event: UtrechtTextboxCustomEvent<any>) => void;
        "pattern"?: string;
        "placeholder"?: string;
        "readOnly"?: boolean;
        "required"?: boolean;
        "type"?: string;
        "value"?: string;
    }
    interface UtrechtUrl {
    }
    interface IntrinsicElements {
        "utrecht-alert": UtrechtAlert;
        "utrecht-article": UtrechtArticle;
        "utrecht-backdrop": UtrechtBackdrop;
        "utrecht-badge-counter": UtrechtBadgeCounter;
        "utrecht-badge-data": UtrechtBadgeData;
        "utrecht-badge-status": UtrechtBadgeStatus;
        "utrecht-breadcrumb": UtrechtBreadcrumb;
        "utrecht-button": UtrechtButton;
        "utrecht-button-group": UtrechtButtonGroup;
        "utrecht-button-link": UtrechtButtonLink;
        "utrecht-checkbox": UtrechtCheckbox;
        "utrecht-code": UtrechtCode;
        "utrecht-code-block": UtrechtCodeBlock;
        "utrecht-contact-card-template": UtrechtContactCardTemplate;
        "utrecht-custom-checkbox": UtrechtCustomCheckbox;
        "utrecht-digid-button": UtrechtDigidButton;
        "utrecht-digid-logo": UtrechtDigidLogo;
        "utrecht-document": UtrechtDocument;
        "utrecht-eherkenning-logo": UtrechtEherkenningLogo;
        "utrecht-eidas-logo": UtrechtEidasLogo;
        "utrecht-emphasis": UtrechtEmphasis;
        "utrecht-form-field-checkbox": UtrechtFormFieldCheckbox;
        "utrecht-form-field-description": UtrechtFormFieldDescription;
        "utrecht-form-field-textarea": UtrechtFormFieldTextarea;
        "utrecht-form-field-textbox": UtrechtFormFieldTextbox;
        "utrecht-form-toggle": UtrechtFormToggle;
        "utrecht-heading": UtrechtHeading;
        "utrecht-heading-1": UtrechtHeading1;
        "utrecht-heading-2": UtrechtHeading2;
        "utrecht-heading-3": UtrechtHeading3;
        "utrecht-heading-4": UtrechtHeading4;
        "utrecht-heading-5": UtrechtHeading5;
        "utrecht-heading-6": UtrechtHeading6;
        "utrecht-heading-group": UtrechtHeadingGroup;
        "utrecht-html-content": UtrechtHtmlContent;
        "utrecht-icon": UtrechtIcon;
        "utrecht-link": UtrechtLink;
        "utrecht-link-button": UtrechtLinkButton;
        "utrecht-logo": UtrechtLogo;
        "utrecht-logo-button": UtrechtLogoButton;
        "utrecht-map-marker": UtrechtMapMarker;
        "utrecht-mark": UtrechtMark;
        "utrecht-number-value": UtrechtNumberValue;
        "utrecht-page": UtrechtPage;
        "utrecht-page-content": UtrechtPageContent;
        "utrecht-page-footer": UtrechtPageFooter;
        "utrecht-page-header": UtrechtPageHeader;
        "utrecht-pagination": UtrechtPagination;
        "utrecht-paragraph": UtrechtParagraph;
        "utrecht-pre-heading": UtrechtPreHeading;
        "utrecht-separator": UtrechtSeparator;
        "utrecht-sidenav": UtrechtSidenav;
        "utrecht-skip-link": UtrechtSkipLink;
        "utrecht-spotlight-section": UtrechtSpotlightSection;
        "utrecht-table": UtrechtTable;
        "utrecht-table-body": UtrechtTableBody;
        "utrecht-table-caption": UtrechtTableCaption;
        "utrecht-table-cell": UtrechtTableCell;
        "utrecht-table-footer": UtrechtTableFooter;
        "utrecht-table-header": UtrechtTableHeader;
        "utrecht-table-header-cell": UtrechtTableHeaderCell;
        "utrecht-table-row": UtrechtTableRow;
        "utrecht-textbox": UtrechtTextbox;
        "utrecht-url": UtrechtUrl;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "utrecht-alert": LocalJSX.UtrechtAlert & JSXBase.HTMLAttributes<HTMLUtrechtAlertElement>;
            "utrecht-article": LocalJSX.UtrechtArticle & JSXBase.HTMLAttributes<HTMLUtrechtArticleElement>;
            "utrecht-backdrop": LocalJSX.UtrechtBackdrop & JSXBase.HTMLAttributes<HTMLUtrechtBackdropElement>;
            "utrecht-badge-counter": LocalJSX.UtrechtBadgeCounter & JSXBase.HTMLAttributes<HTMLUtrechtBadgeCounterElement>;
            "utrecht-badge-data": LocalJSX.UtrechtBadgeData & JSXBase.HTMLAttributes<HTMLUtrechtBadgeDataElement>;
            "utrecht-badge-status": LocalJSX.UtrechtBadgeStatus & JSXBase.HTMLAttributes<HTMLUtrechtBadgeStatusElement>;
            "utrecht-breadcrumb": LocalJSX.UtrechtBreadcrumb & JSXBase.HTMLAttributes<HTMLUtrechtBreadcrumbElement>;
            "utrecht-button": LocalJSX.UtrechtButton & JSXBase.HTMLAttributes<HTMLUtrechtButtonElement>;
            "utrecht-button-group": LocalJSX.UtrechtButtonGroup & JSXBase.HTMLAttributes<HTMLUtrechtButtonGroupElement>;
            "utrecht-button-link": LocalJSX.UtrechtButtonLink & JSXBase.HTMLAttributes<HTMLUtrechtButtonLinkElement>;
            "utrecht-checkbox": LocalJSX.UtrechtCheckbox & JSXBase.HTMLAttributes<HTMLUtrechtCheckboxElement>;
            "utrecht-code": LocalJSX.UtrechtCode & JSXBase.HTMLAttributes<HTMLUtrechtCodeElement>;
            "utrecht-code-block": LocalJSX.UtrechtCodeBlock & JSXBase.HTMLAttributes<HTMLUtrechtCodeBlockElement>;
            "utrecht-contact-card-template": LocalJSX.UtrechtContactCardTemplate & JSXBase.HTMLAttributes<HTMLUtrechtContactCardTemplateElement>;
            "utrecht-custom-checkbox": LocalJSX.UtrechtCustomCheckbox & JSXBase.HTMLAttributes<HTMLUtrechtCustomCheckboxElement>;
            "utrecht-digid-button": LocalJSX.UtrechtDigidButton & JSXBase.HTMLAttributes<HTMLUtrechtDigidButtonElement>;
            "utrecht-digid-logo": LocalJSX.UtrechtDigidLogo & JSXBase.HTMLAttributes<HTMLUtrechtDigidLogoElement>;
            "utrecht-document": LocalJSX.UtrechtDocument & JSXBase.HTMLAttributes<HTMLUtrechtDocumentElement>;
            "utrecht-eherkenning-logo": LocalJSX.UtrechtEherkenningLogo & JSXBase.HTMLAttributes<HTMLUtrechtEherkenningLogoElement>;
            "utrecht-eidas-logo": LocalJSX.UtrechtEidasLogo & JSXBase.HTMLAttributes<HTMLUtrechtEidasLogoElement>;
            "utrecht-emphasis": LocalJSX.UtrechtEmphasis & JSXBase.HTMLAttributes<HTMLUtrechtEmphasisElement>;
            "utrecht-form-field-checkbox": LocalJSX.UtrechtFormFieldCheckbox & JSXBase.HTMLAttributes<HTMLUtrechtFormFieldCheckboxElement>;
            "utrecht-form-field-description": LocalJSX.UtrechtFormFieldDescription & JSXBase.HTMLAttributes<HTMLUtrechtFormFieldDescriptionElement>;
            "utrecht-form-field-textarea": LocalJSX.UtrechtFormFieldTextarea & JSXBase.HTMLAttributes<HTMLUtrechtFormFieldTextareaElement>;
            "utrecht-form-field-textbox": LocalJSX.UtrechtFormFieldTextbox & JSXBase.HTMLAttributes<HTMLUtrechtFormFieldTextboxElement>;
            "utrecht-form-toggle": LocalJSX.UtrechtFormToggle & JSXBase.HTMLAttributes<HTMLUtrechtFormToggleElement>;
            "utrecht-heading": LocalJSX.UtrechtHeading & JSXBase.HTMLAttributes<HTMLUtrechtHeadingElement>;
            "utrecht-heading-1": LocalJSX.UtrechtHeading1 & JSXBase.HTMLAttributes<HTMLUtrechtHeading1Element>;
            "utrecht-heading-2": LocalJSX.UtrechtHeading2 & JSXBase.HTMLAttributes<HTMLUtrechtHeading2Element>;
            "utrecht-heading-3": LocalJSX.UtrechtHeading3 & JSXBase.HTMLAttributes<HTMLUtrechtHeading3Element>;
            "utrecht-heading-4": LocalJSX.UtrechtHeading4 & JSXBase.HTMLAttributes<HTMLUtrechtHeading4Element>;
            "utrecht-heading-5": LocalJSX.UtrechtHeading5 & JSXBase.HTMLAttributes<HTMLUtrechtHeading5Element>;
            "utrecht-heading-6": LocalJSX.UtrechtHeading6 & JSXBase.HTMLAttributes<HTMLUtrechtHeading6Element>;
            "utrecht-heading-group": LocalJSX.UtrechtHeadingGroup & JSXBase.HTMLAttributes<HTMLUtrechtHeadingGroupElement>;
            "utrecht-html-content": LocalJSX.UtrechtHtmlContent & JSXBase.HTMLAttributes<HTMLUtrechtHtmlContentElement>;
            "utrecht-icon": LocalJSX.UtrechtIcon & JSXBase.HTMLAttributes<HTMLUtrechtIconElement>;
            "utrecht-link": LocalJSX.UtrechtLink & JSXBase.HTMLAttributes<HTMLUtrechtLinkElement>;
            "utrecht-link-button": LocalJSX.UtrechtLinkButton & JSXBase.HTMLAttributes<HTMLUtrechtLinkButtonElement>;
            "utrecht-logo": LocalJSX.UtrechtLogo & JSXBase.HTMLAttributes<HTMLUtrechtLogoElement>;
            "utrecht-logo-button": LocalJSX.UtrechtLogoButton & JSXBase.HTMLAttributes<HTMLUtrechtLogoButtonElement>;
            "utrecht-map-marker": LocalJSX.UtrechtMapMarker & JSXBase.HTMLAttributes<HTMLUtrechtMapMarkerElement>;
            "utrecht-mark": LocalJSX.UtrechtMark & JSXBase.HTMLAttributes<HTMLUtrechtMarkElement>;
            "utrecht-number-value": LocalJSX.UtrechtNumberValue & JSXBase.HTMLAttributes<HTMLUtrechtNumberValueElement>;
            /**
             * @license EUPL-1.2
             * Copyright (c) 2021 Gemeente Utrecht
             */
            "utrecht-page": LocalJSX.UtrechtPage & JSXBase.HTMLAttributes<HTMLUtrechtPageElement>;
            /**
             * @license EUPL-1.2
             * Copyright (c) 2021 Gemeente Utrecht
             */
            "utrecht-page-content": LocalJSX.UtrechtPageContent & JSXBase.HTMLAttributes<HTMLUtrechtPageContentElement>;
            /**
             * @license EUPL-1.2
             * Copyright (c) 2021 Gemeente Utrecht
             */
            "utrecht-page-footer": LocalJSX.UtrechtPageFooter & JSXBase.HTMLAttributes<HTMLUtrechtPageFooterElement>;
            /**
             * @license EUPL-1.2
             * Copyright (c) 2021 Gemeente Utrecht
             */
            "utrecht-page-header": LocalJSX.UtrechtPageHeader & JSXBase.HTMLAttributes<HTMLUtrechtPageHeaderElement>;
            "utrecht-pagination": LocalJSX.UtrechtPagination & JSXBase.HTMLAttributes<HTMLUtrechtPaginationElement>;
            "utrecht-paragraph": LocalJSX.UtrechtParagraph & JSXBase.HTMLAttributes<HTMLUtrechtParagraphElement>;
            "utrecht-pre-heading": LocalJSX.UtrechtPreHeading & JSXBase.HTMLAttributes<HTMLUtrechtPreHeadingElement>;
            "utrecht-separator": LocalJSX.UtrechtSeparator & JSXBase.HTMLAttributes<HTMLUtrechtSeparatorElement>;
            "utrecht-sidenav": LocalJSX.UtrechtSidenav & JSXBase.HTMLAttributes<HTMLUtrechtSidenavElement>;
            "utrecht-skip-link": LocalJSX.UtrechtSkipLink & JSXBase.HTMLAttributes<HTMLUtrechtSkipLinkElement>;
            "utrecht-spotlight-section": LocalJSX.UtrechtSpotlightSection & JSXBase.HTMLAttributes<HTMLUtrechtSpotlightSectionElement>;
            "utrecht-table": LocalJSX.UtrechtTable & JSXBase.HTMLAttributes<HTMLUtrechtTableElement>;
            "utrecht-table-body": LocalJSX.UtrechtTableBody & JSXBase.HTMLAttributes<HTMLUtrechtTableBodyElement>;
            "utrecht-table-caption": LocalJSX.UtrechtTableCaption & JSXBase.HTMLAttributes<HTMLUtrechtTableCaptionElement>;
            "utrecht-table-cell": LocalJSX.UtrechtTableCell & JSXBase.HTMLAttributes<HTMLUtrechtTableCellElement>;
            "utrecht-table-footer": LocalJSX.UtrechtTableFooter & JSXBase.HTMLAttributes<HTMLUtrechtTableFooterElement>;
            "utrecht-table-header": LocalJSX.UtrechtTableHeader & JSXBase.HTMLAttributes<HTMLUtrechtTableHeaderElement>;
            "utrecht-table-header-cell": LocalJSX.UtrechtTableHeaderCell & JSXBase.HTMLAttributes<HTMLUtrechtTableHeaderCellElement>;
            "utrecht-table-row": LocalJSX.UtrechtTableRow & JSXBase.HTMLAttributes<HTMLUtrechtTableRowElement>;
            "utrecht-textbox": LocalJSX.UtrechtTextbox & JSXBase.HTMLAttributes<HTMLUtrechtTextboxElement>;
            "utrecht-url": LocalJSX.UtrechtUrl & JSXBase.HTMLAttributes<HTMLUtrechtUrlElement>;
        }
    }
}
