import { ThemeVars } from '@storybook/theming';

export const theme: ThemeVars = {
  appBg: '#e6e6e6',
  appBorderColor: '#666666',
  appBorderRadius: 0,
  appContentBg: '#ffffff',
  barBg: '#D0D0D0',
  barSelectedColor: 'green',
  barTextColor: '#000000',
  base: 'light',
  booleanBg: '#ffffff',
  booleanSelectedBg: '#255A93',
  brandImage: 'logo.svg',
  brandTitle: 'Gemeente Utrecht',
  brandUrl: 'https://www.utrecht.nl',
  buttonBg: '#ffffff',
  buttonBorder: '#24578F',
  colorPrimary: '#2964a3',
  colorSecondary: '#1b4050',
  fontBase: '"Lucida Grande", "Lucida Sans Unicode", "Lucida Sans", Verdana, sans-serif',
  fontCode: 'monospace',
  inputBg: '#ffffff',
  inputBorder: '#4D4D4D',
  inputBorderRadius: 0,
  inputTextColor: '#000000',
  textColor: '#1d1d1c',
  textInverseColor: '#ffffff',
  textMutedColor: '#727272',
};
